index.rst
retrieval/about_ena.rst

about ena doc

---

submit/analyses.rst
submit/reads/programmatic.rst
submit/samples/programmatic.md
submit/study/programmatic.md

Edited a few more ftp links to https as discussed in [issue 40](https://github.com/enasequence/read_docs/issues/40#issuecomment-979811773)

update ftp links to https protocol

---

retrieval/file-download.rst

Updating file-download.rst with github link to command-line-downloader

---

retrieval/file-download/sra-ftp-structure.rst

URL link correction

---

submit/general-guide/programmatic.md

Remove DAC, Policy and Dataset XML Schemas

Remove EGA data types

---

submit/sequence/webin-cli-spreadsheet.rst

Update links to annotated sequence checklists

Fix broken links

---

submit/sequence/annotation-checklists.rst

Remove the section on virtual transcripts as that checklist does not exist anymore.

Update CDS mRNA description

---

submit/general-guide/programmatic-v2.rst

Programmatic webin rest V2 documentation file

Webin rest V2 documentation

---

submit/general-guide/programmatic.md

Add separate heading for Webin V2 API and include link to documentation

Include link to Webin V2

---

submit/general-guide/programmatic-v2.rst

Update example XML Webin block. Update line spacing between XML Schemas and urls. Update table new lines

Update line spacing

---

submit/general-guide/webin-cli.md

Add link to ENA Webin-CLI Bulk submissions tool.

ENA bulk submissions tool

---

submit/samples/programmatic.md

Add missing mandatory attribute 'project name' to Sample XML.

Add sample attribute

---

submit/reads/programmatic.rst

Add multi fastq xml to programmatic submission

Update to add multi-Fastq

---

submit/fileprep/reads.md

Update single cell read data documentation to add paragraph on multi-fastq support

Add multi-fastq info

---

submit/fileprep/reads.md

Updated CASAVA regex as per the latest webin-cli 5.2.0 updates to accept valid read names.

CASAVA regex update

---

faq/data_brokering.rst

Data brokers responsibilities and why they cannot suppress/cancel data.

Update data brokering page

---

faq/release/data-availability-policy.rst

Update status from confidential to private so its consistent with INSDC.

Update private status

---

faq/data_brokering.rst

as per a past content meeting, added text on ENA-announce in the brokering documentation

Added ENA-announce text

---

submit/general-guide/webin-cli.md

Include that aspera is useful for larger files based on submitter feedback

Update aspera wording

---

faq/pathogen-subs-guide.rst

tabs removed due to issue with rendering

Jas mckin pathogen guide remove tabs

---

submit/reads/webin-cli.md

Correct typo in 'spatial_barcode'

Update webin-cli multi-fastq.md

---

faq/pathogen-subs-guide.rst

fix bacterial chromosome list file example

Jas mckin pathogen guide

---

.readthedocs.yaml
conf.py
faq/pathogen-subs-guide.rst
faq/taxonomy.rst
requirements.txt

Update the readthedocs configuration. This includes adding a .readthedocs.yaml file, and making some additions to the config.py file. sphinx-tabs and myst_parser packages were added to the requirements.txt file.
sphinx-tabs adds tabs functionality, as described at https://sphinx-tabs.readthedocs.io/en/latest/
myst_parser in requirements.txt permits the sphinx theme to continue to be able to display .md files in addition to .rst files under the new config.

Config update

---

submit/analyses/bionano-maps.md
submit/analyses/pacbio-methylation.md
submit/analyses/read-alignments.md
submit/analyses/sequence-annotation.md
submit/general-guide/webin-cli.md
submit/reads/webin-cli.md
submit/samples/programmatic.md
submit/study/programmatic.md
update/metadata/programmatic-read.md
update/metadata/programmatic-sample.md
update/metadata/programmatic-study.md

Reverts enasequence/read_docs#137

Revert "Correct URLs for .md files"

---

retrieval/programmatic-access.rst
retrieval/programmatic-access/tag_querying.rst

A user article about the availability of tags and how it use them.
(I tried submitting this via push, but still able to push to this repo after a week, so simply pasting this into a new file via GitHub)

Created tag_querying.rst

---

submit/reads/webin-cli.md

Updated webin-cli.md with new instruments and platforms with changes as seen in https://github.com/enasequence/webin-cli/releases/tag/6.6.0 more info in our DCA Jira: 
https://www.ebi.ac.uk/panda/jira/secure/RapidBoard.jspa?rapidView=145&projectKey=DCP&view=planning&selectedIssue=DCP-3844&quickFilter=407&issueLimit=100
Alisha or Maira, please can one of you check, if necessary update and push?
@ihsann1  @alisha246

Updated webin-cli.md with new instruments and platforms

---

conf.py
submit/general-guide/webin-cli.md

-adds java 17 link to submit/general-guide/webin-cli.md 
-update licensing date on conf.py

add java 17 link

---

submit/samples/interactive.rst

Checked accepted spreadsheet format and updated documentation

Updated accepted spreadsheet format

---

update/assembly.rst

updated time for submission

---

faq/runs.rst

Update image link in runs.rst

---

faq/runs.rst

Changed from pink box to highlighted in pink

change wording
